cabinetoffice/gap-find-apply-web

packages/admin/.snyk
packages/applicant/.snyk
packages/applicant/jest.config.js
packages/applicant/package.json
packages/applicant/setupJestMock.js
packages/applicant/src/middleware.page.ts
packages/applicant/src/middleware.test.ts
yarn.lock

Amends applicant middleware to direct user to root applicant page (ie the page that asks you to register or login) when user not logged in or error reading JWT.
Adds test suite for applicant `middleware.page.ts`.
Installs polyfills required for above test to work in Node 16.

redirect to applicant base url when user not logged in

---

packages/admin/src/pages/super-admin-dashboard/manage-departments/add/index.page.tsx
packages/admin/src/pages/super-admin-dashboard/manage-departments/edit/[id]/index.page.tsx
packages/admin/src/pages/super-admin-dashboard/manage-departments/index.page.tsx
packages/gap-web-ui/src/components/summary-list/SummaryList.tsx

Includes SummaryList changes to add bold headers

Fix some styles & copy

---

packages/admin/src/pages/dashboard/index.page.tsx
packages/admin/src/pages/dashboard/index.test.tsx
packages/admin/src/pages/scheme/[schemeId]/advert/[advertId]/section-overview.page.tsx
packages/admin/src/services/SchemeService.ts
packages/applicant/src/pages/dashboard/Dashboard.test.tsx
packages/applicant/src/pages/dashboard/Dashboard.tsx
packages/applicant/src/pages/dashboard/index.page.test.tsx
packages/applicant/src/pages/dashboard/index.page.tsx
packages/gap-web-ui/src/components/notification-banner/ImportantBanner.stories.tsx
packages/gap-web-ui/src/components/notification-banner/ImportantBanner.test.tsx
packages/gap-web-ui/src/components/notification-banner/ImportantBanner.tsx
packages/gap-web-ui/src/utils/UnitTestHelpers.tsx
yarn.lock

Upon logging in for the first time, users with COLA subs are migrated in the backend. A query param is sent up to the frontend which determines what banner to show. Upon subsequent logins, they will not see this banner.
Admin failed to migrate:
Admin successfully migrated:
Banner storybooks:

Migration error/success banners

---

packages/applicant/.env.example
packages/applicant/src/middleware.page.ts
packages/applicant/src/pages/dashboard/Dashboard.test.tsx
packages/applicant/src/pages/dashboard/Dashboard.tsx
packages/applicant/src/pages/dashboard/index.page.test.tsx
packages/applicant/src/pages/dashboard/index.page.tsx
packages/applicant/src/pages/sign-in-details/index.page.test.tsx
packages/applicant/src/pages/sign-in-details/index.page.tsx
packages/applicant/src/utils/routes.tsx

Adds a new 'Change your sign in details' card to the Applicant dashboard when the OneLogin feature flag is enabled.
Adds a OneLogin information screen 9behind a OneLogin feature flag) and a offsite link to OneLogin.

GAP-1927: [Applicant] - Edit log in details

---

.github/workflows/feature.yml
packages/admin/next.config.js
packages/admin/setupJestMock.js
packages/admin/src/pages/super-admin-dashboard/Navigation.test.tsx
packages/admin/src/pages/super-admin-dashboard/Navigation.tsx
packages/admin/src/pages/super-admin-dashboard/index.page.tsx

Adds a new navigation bar item for user that have TECHNICAL_SUPPORT role.
this item will not be shown otherwise.

Add TechnicalSupport navigation bar item

---

packages/admin/src/pages/super-admin-dashboard/index.page.tsx
packages/admin/src/utils/fetchDataOrGetRedirect.test.ts
packages/admin/src/utils/fetchDataOrGetRedirect.ts
packages/gap-web-ui/src/components/question-page/CallServiceMethod.tsx
packages/gap-web-ui/src/components/question-page/QuestionPageGetServerSideProps.tsx
packages/gap-web-ui/src/components/question-page/QuestionPageGetServerSidePropsTypes.ts

- adds a new prop in QuestionPageGetServerSideProps for custom fetchPageData error handling
- fetchPageDataOrRedirect redirects to login screen when the user is not logged in
related pr: https://github.com/cabinetoffice/gap-find-admin-backend/pull/13

GAP-2088 (redirects)

---

packages/applicant/src/pages/index.page.test.tsx
packages/applicant/src/pages/index.page.tsx

2117 Notice Page Feature Flag

---

packages/admin/src/pages/super-admin-dashboard/manage-departments/index.page.tsx

Issue was that to render the column headings we were checking for the first index of the array, which was the Cabinet office department.
Fix was to remove that check instead adding the columns always to the first index of the department array

Gap 2131 fix manage departments

---

packages/admin/src/pages/build-application/[applicationId]/[sectionId]/question-type.page.tsx
packages/admin/src/pages/build-application/[applicationId]/[sectionId]/question-type.test.tsx
packages/gap-web-ui/src/components/question-page/inputs/DocumentUpload.test.tsx
packages/gap-web-ui/src/components/question-page/inputs/DocumentUpload.tsx

GAP-2188 (https://technologyprogramme.atlassian.net/browse/GAP-2188)
Guidance was inconsistent between applicant and admin view for document upload selection. Content for grant admins was changed to  be - "Allows files that are .DOC, .DOCX, .ODT, .PDF, .XLS, .XLSX or .ZIP"
Document Upload selection
Document Upload preview
Screenshot attached which shows the new text added for document upload description when being viewed by admins.

Gap 2188 fix copy for document upload

---

.github/workflows/feature.yml
package.json
packages/admin/.snyk
packages/admin/src/pages/scheme/[schemeId]/download-submissions.page.tsx
packages/admin/src/pages/scheme/[schemeId]/download-submissions.test.tsx
packages/applicant/.snyk
yarn.lock

Ticket [2230](https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2230)

GAP-2230: frontend times out when requesting many submissions

---

packages/applicant/src/pages/submissions/[submissionId]/sections.page.test.tsx
packages/applicant/src/pages/submissions/[submissionId]/sections.page.tsx
packages/applicant/src/services/ApplicationService.tsx

Ticket # and link - https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2218
Consumes new applicant endpoint and redirects to grant-is-closed when the application has been closed
related prs:
https://github.com/cabinetoffice/gap-find-applicant-backend/pull/22
https://github.com/cabinetoffice/gap-find-lambda-scheduled-publishing/pull/4
https://github.com/cabinetoffice/gap-find-admin-backend/pull/42

Redirect to grant-is-closed when application is REMOVED

---

packages/admin/src/pages/_app.page.js
packages/applicant/src/pages/_app.page.js
packages/gap-web-ui/rollup.config.js

Fixes the client occasionally breaking on chrome when following a next link, and fixes Safari and Firefox reliably breaking as a result of fixing the first error.

fix client-side js crashing in webkit and firefox

---

packages/applicant/src/middleware.page.ts
packages/applicant/src/pages/index.page.test.tsx
packages/applicant/src/pages/index.page.tsx

Currently the redirect url is defaulted and set in the env var (V2_LOGIN_URL)
This change adds redirect url to user-service call if navigating directly to mandatory questions start page
- Updates index page to override login redirect url if one is passed in, this is then sent to user-service
- Added check in the middleware to set redirectUrl to the mandatory question start page
- Added unit tests to cover redirectUrl existing and being undefined
https://technologyprogramme.atlassian.net/browse/TMI2-440

Adds redirect url to user-service call if navigating directly to mandatory questions start page

---

.github/workflows/admin-ci.yml
.github/workflows/admin-sandbox-qa-cd.yml
.github/workflows/applicant-ci.yml
.github/workflows/applicant-sandbox-qa-cd.yml
.github/workflows/gap-web-ui-ci.yml

Now triggers on creation & pushes to develop or release branches
- Removing unnecessary contents read permissions
- Annoyingly create cant specify branches, so an additional check is needed per job as per: https://github.com/orgs/community/discussions/26286#discussioncomment-3251208

Fix trigger CD on push & create

---

packages/applicant/src/pages/mandatory-questions/[mandatoryQuestionId]/organisation-address.page.tsx
packages/applicant/src/pages/mandatory-questions/[mandatoryQuestionId]/organisation-address.test.tsx
packages/applicant/src/pages/mandatory-questions/[mandatoryQuestionId]/organisation-name.page.tsx
packages/applicant/src/pages/mandatory-questions/[mandatoryQuestionId]/organisation-name.test.tsx

Adds conditional logic to name and address
[GAP-2247](https://technologyprogramme.atlassian.net/browse/GAP-2247?atlOrigin=eyJpIjoiOTEwYzI1MzYxNWYxNDU1Nzg5NmEyOGMwOGM1ZGJjMDYiLCJwIjoiaiJ9)
Adds ternary logic for name and address content displays
[GAP-2247]: https://technologyprogramme.atlassian.net/browse/GAP-2247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GAP-2247 Add conditional logic to name and address

---

packages/admin/src/utils/QuestionPageGetServerSideProps.tsx
packages/applicant/src/pages/api/submissions/[submissionId]/sections/[sectionId]/questions/[questionId]/upload-file.page.tsx

Sanitizes filename to safely remove characters that may be a threat or cause content disposition errors.
This is now consistent with the backend.
Tested with `testing ,.'";}{()%^*+£$!|.xlsx` and it will convert to `testing_,._____()________.xlsx`
https://technologyprogramme.atlassian.net/browse/GAP-2233

Sanitises filename to prevent Content Disposition error

---

packages/admin/src/pages/scheme/[schemeId]/manage-due-diligence-checks.page.tsx
packages/admin/src/pages/scheme/[schemeId]/manage-due-diligence-checks.test.tsx

- change in requirements to not have the login button display when it is an external application
TMI2-390 - https://technologyprogramme.atlassian.net/browse/TMI2-390
External application
Internal application

TMI2-390: removed spotlight login for external applications

---

packages/admin/src/pages/api/downloadDueDiligenceChecks.page.ts
packages/admin/src/pages/api/downloadRequiredChecks.page.ts
packages/admin/src/pages/api/downloadRequiredChecks.test.ts
packages/admin/src/pages/api/downloadSpotlightChecks.page.ts
packages/admin/src/pages/api/downloadSpotlightChecks.test.ts
packages/admin/src/pages/scheme/[schemeId]/manage-due-diligence-checks.test.tsx
packages/admin/src/pages/scheme/components/SchemeApplications.tsx

The link on the 'Please return' text on the service error page was incorrect and this has been updated with the correct hrefs
TMI2-422 https://technologyprogramme.atlassian.net/browse/TMI2-422

TMI2-422: updated service-error page hrefs

---

packages/admin/package.json
packages/applicant/package.json
yarn.lock

Ticket # and link [GAP-2301](https://technologyprogramme.atlassian.net/browse/GAP-2301?atlOrigin=eyJpIjoiNmY2MWI0MmQ5ODA0NGZkNDljNDFiNjExNWEyNzc4YzMiLCJwIjoiaiJ9)
Original intent was to update to 12.3.3 to fix the 504 issue but this change attempts to synchronise our nextjs version with out find-fe which is already using 12.3.4
[GAP-2301]: https://technologyprogramme.atlassian.net/browse/GAP-2301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GAP:2301 Update Next to 12.3.4

---

packages/admin/src/pages/scheme/[schemeId]/manage-due-diligence-checks.page.tsx
packages/admin/src/pages/scheme/[schemeId]/manage-due-diligence-checks.test.tsx
packages/admin/src/services/MandatoryQuestionsService.test.ts
packages/admin/src/services/MandatoryQuestionsService.ts

A missed scenario in the ticket was to not show the spotlight download link if there are no completed mandatory questions of the specified org type
TMI2-422 - https://technologyprogramme.atlassian.net/browse/TMI2-422

TMI2-422: doesn't show link if no spotlight data to download

---

packages/admin/src/pages/build-application/[applicationId]/unpublish-confirmation.page.tsx
packages/admin/src/pages/build-application/[applicationId]/unpublish-confirmation.test.tsx

[Ticket TMI2-499](https://technologyprogramme.atlassian.net/jira/software/projects/TMI2/boards/331?selectedIssue=TMI2-499)
- Fixing the layout from 1/3rd to 2/3rds for the unpublish application admin page
Before:
After:

TMI2-499: Fixing layout of unpublish application page

---

packages/admin/src/pages/scheme/[schemeId]/advert/[advertId]/unpublish-confirmation.page.tsx

[Ticket TMI2-499](https://technologyprogramme.atlassian.net/jira/software/projects/TMI2/boards/331?selectedIssue=TMI2-499)
- Turns out the advert unpublish page also has the same layout issue - fixing from 1/3rd to 2/3rds
Before:
After:

TMI2-499: Fixing layout of unpublish advert page

---

packages/admin/src/pages/super-admin-dashboard/types.ts
packages/admin/src/pages/super-admin-dashboard/user/[id]/index.page.tsx
packages/admin/src/services/SchemeService.ts

Checks if user has (one login) sub, if user is un-migrated and therefore sub is null we use their cola sub.
https://technologyprogramme.atlassian.net/browse/GAP-2336

Checks user sub and uses colaSub if it doesn't exist

---

packages/admin/src/utils/general.ts
packages/applicant/.env.example
packages/applicant/src/components/partials/Header.tsx
packages/applicant/src/pages/api/create-submission.page.tsx
packages/applicant/src/pages/api/create-submission.test.tsx
packages/applicant/src/pages/mandatory-questions/[mandatoryQuestionId]/organisation-summary.page.test.tsx
packages/applicant/src/pages/mandatory-questions/[mandatoryQuestionId]/organisation-summary.page.tsx
packages/applicant/src/utils/routes.test.tsx
packages/applicant/src/utils/routes.tsx

Due to what seems to be a bug with Nextjs 12.3.4 having identically named subfolders in both `/pages` and `/page/api` directories causes Nextjs to mistakenly treat the latter as pages, meaning the redirects from these API routes are not respected.

fix api folder causing buggy behaviour

---

packages/admin/src/utils/QuestionPageGetServerSideProps.test.tsx
packages/admin/src/utils/QuestionPageGetServerSideProps.tsx
packages/admin/src/utils/QuestionPageGetServerSidePropsTypes.ts

When using `QuestionPageGetServerSideProps`, allows for the use of pageData within the handleRequest function & supports all the generic typing.
E.g.
``` 
async function handleRequest(
body: PageBodyResponse,
jwt: string,
pageData: Awaited<ReturnType<typeof fetchPageData>>
) {
console.log(pageData);
await checkNewAdminEmailIsValid(
jwt,
getUserTokenFromCookies(context.req),
body.emailAddress,
oldEmailAddress
);
return body.emailAddress;
}

Passing in pageData to handleRequest function

---

packages/admin/src/pages/_document.page.tsx
packages/admin/src/styles/globals.scss
packages/applicant/src/pages/_document.page.tsx
packages/applicant/src/styles/globals.scss

Changed the root background colour to the same grey colour as the footer
https://technologyprogramme.atlassian.net/browse/TMI2-518

TD-166: fix white space below footer

---

packages/applicant/src/pages/submissions/[submissionId]/sections/[sectionId]/index.page.test.tsx
packages/applicant/src/pages/submissions/[submissionId]/sections/[sectionId]/index.page.tsx
packages/applicant/src/services/SubmissionService.test.ts
packages/applicant/src/services/SubmissionService.tsx

Makes call to backend to check the eligibility response on submission sections overview page. False is returned if the response is 'No' and the user will not be able to submit the application or fill out the other sections. Even if the user tries to navigate to these sections through the URL, they will be redirected to the submission sections overview page.
TD-150: https://technologyprogramme.atlassian.net/browse/TD-150

TD-150: redirects user if eligibility sections response is no

---

packages/admin/src/middleware.page.ts
packages/admin/src/middleware.test.ts

[Dashboard link not working for applicant on 404 error page](https://technologyprogramme.atlassian.net/jira/software/projects/TMI2/boards/331?selectedIssue=TMI2-522)
Admin middleware required additional logic to redirect an applicant attempting to access admin pages. The error page in the ticket should never be accessible to an applicant as it is the **admin** error page (hence the dashboard link not working - the admin error page is trying to redirect to the admin dashboard).
https://github.com/cabinetoffice/gap-find-apply-web/assets/107405237/734fe279-7c0a-4abb-ad3d-72fc58a9adad

TMI2-522 - Added logic to redirect applicant without valid session-id cookie

---

packages/applicant/src/pages/mandatory-questions/start.page.test.tsx
packages/applicant/src/pages/mandatory-questions/start.page.tsx

Ticket [GAP-2365](https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2365)
- When an application status is REMOVED (unpublished), then throwing an error before starting MQ journey
- https://github.com/cabinetoffice/gap-find-applicant-backend/pull/87
https://github.com/cabinetoffice/gap-find-apply-web/assets/101722961/bea658b8-c150-4404-9720-c1d77ef4f998
[GAP-2365]: https://technologyprogramme.atlassian.net/browse/GAP-2365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLC …

GAP-2365: Throwing error if application has been unpublished

---

packages/admin/src/pages/scheme/[schemeId]/advert/[advertId]/summary/components/List.tsx
packages/admin/src/pages/scheme/[schemeId]/advert/[advertId]/summary/components/RichText.tsx

[TMI2-515 - Admin summary page doesn't look right on safari](https://technologyprogramme.atlassian.net/jira/software/projects/TMI2/boards/331?selectedIssue=TMI2-515)
Isolated the fields causing the rendering errors with divs. This causes no visible differences to rendering in Chrome while fixing the errors in Safari.
https://github.com/cabinetoffice/gap-find-apply-web/assets/107405237/59ca6542-2885-4a8f-8c62-baa82282ac10

TMI2-515 - Fixed line breaks in advert summary page on Safari

---

packages/admin/src/pages/super-admin-dashboard/manage-departments/index.page.tsx
packages/admin/src/pages/super-admin-dashboard/manage-departments/manage-departments.module.scss
packages/gap-web-ui/src/components/summary-list/SummaryList.tsx

[TMI2-589 - Super admin department list formatting strange on safari](https://technologyprogramme.atlassian.net/jira/software/projects/TMI2/boards/331?selectedIssue=TMI2-589)
Isolated the fields causing the rendering errors with divs. This causes no visible differences to rendering in Chrome while fixing the errors in Safari.
https://github.com/cabinetoffice/gap-find-apply-web/assets/107405237/da6b83e7-99b5-4366-bac5-3f64543608e8

TMI2-589 - Fixed line breaks in super admin department page on Safari

---

packages/applicant/src/pages/api/routes/submissions/[submissionId]/download-summary.page.tsx
packages/applicant/src/pages/api/routes/submissions/[submissionId]/download-summary.test.tsx
packages/applicant/src/pages/submissions/[submissionId]/summary.page.tsx
packages/applicant/src/services/SubmissionService.tsx
packages/applicant/src/utils/routes.tsx

Adds an api route which sends the odt submission summary to the browser
https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2097
related prs: 
- https://github.com/cabinetoffice/gap-user-service/pull/175
- https://github.com/cabinetoffice/gap-find-applicant-backend/pull/89

GAP-2097: Download submission summary

---

packages/applicant/src/middleware.page.ts
packages/applicant/src/middleware.test.ts
packages/applicant/src/pages/mandatory-questions/start.page.test.tsx
packages/applicant/src/pages/mandatory-questions/start.page.tsx

Previous PR broke Mandatory Questions grant-is-closed logic as it was assuming it was a submission ID that is parse in the URL. This changes it to dynamically hit the backend based on if its a Question ID or a Submission ID
GAP:2360
Dependent on https://github.com/cabinetoffice/gap-find-applicant-backend/pull/96
Implemented endpoint to function.

GAP-2360: Fix mandatory questions grant-is-closed journeys

---

packages/applicant/src/pages/grant-is-closed.page.test.tsx
packages/applicant/src/pages/grant-is-closed.page.tsx

Was agreed it didn't make sense to let the user "back" into a closed grant to be redirected to the same page. Also didn't work.
GAP:2360

GAP-2360: Remove back button on grant-is-closed

---

packages/admin/next.config.js
packages/applicant/next.config.js

Removing the "swc-disabled" message as per docs https://nextjs.org/docs/messages/swc-disabled
I was unable to remove babel entirely as jest is extremely difficult to configure due to the monorepo nature of our apps. However this change should give us most of the benefits of SWC being:
> This new compiler is up to 17x faster than Babel when compiling individual files and up to 5x faster Fast Refresh.

Replacing next transforms with SWC over babel

---

packages/admin/src/pages/build-application/[applicationId]/components/Sections.tsx
packages/admin/src/pages/build-application/[applicationId]/dashboard.page.tsx
packages/gap-web-ui/src/components/question-page/FlexibleQuestionPageLayout.tsx

Retains scroll position after shifting sections
This is just an enhancement - still functions without javascript
https://github.com/cabinetoffice/gap-find-apply-web/assets/101722961/b0b7f55e-e508-44ee-b0f4-e4a1d1377522

GAP-2102: Retain scroll position after moving sections

---

packages/applicant/src/pages/dashboard/Dashboard.tsx

changing from Link to anchor tag should prevent next from prefetching this page, which means that Cypress will not attempt to open it and thus won't be "logged out"
[GAP-2410](https://technologyprogramme.atlassian.net/browse/GAP-2410)
[GAP-2410]: https://technologyprogramme.atlassian.net/browse/GAP-2410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GAP-2410 | Fix flaky E2E tests RE Sign In Details

---

packages/admin/src/pages/build-application/[applicationId]/[sectionId]/question-type.page.tsx
packages/admin/src/pages/build-application/[applicationId]/[sectionId]/question-type.test.tsx
packages/admin/src/services/QuestionService.ts
packages/applicant/src/pages/submissions/[submissionId]/sections/[sectionId]/questions/[questionId]/index.page.tsx
packages/gap-web-ui/src/components/question-page/inputs/TextArea.tsx
packages/gap-web-ui/src/components/question-page/inputs/TextInput.tsx
packages/gap-web-ui/src/components/question-page/inputs/constants/index.ts

adds default word count validation to text / textarea questions 
https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2397
Related pr: https://github.com/cabinetoffice/gap-find-admin-backend/pull/169

GAP-2973: word count validation

---

packages/admin/src/pages/scheme/[schemeId]/advert/[advertId]/summary/components/PublishOrScheduleButton.tsx
packages/gap-web-ui/src/components/question-page/FlexibleQuestionPageLayout.tsx
packages/gap-web-ui/src/components/question-page/inputs/Button.tsx

When the publish button is clicked, it is disabled and the form is submitted so that the user cannot click the button multiple times. This will not work with javascript
TMI2-596: https://technologyprogramme.atlassian.net/browse/TMI2-596

TMI2-596: disable publish button onClick

---

packages/applicant/src/pages/api/routes/submissions/[submissionId]/sections/[sectionId]/questions/[questionId]/attachments/[attachmentId]/remove.page.tsx
packages/applicant/src/pages/api/routes/submissions/[submissionId]/sections/[sectionId]/questions/[questionId]/attachments/[attachmentId]/remove.test.tsx
packages/applicant/src/pages/api/routes/submissions/[submissionId]/sections/[sectionId]/questions/[questionId]/upload-file.page.tsx
packages/applicant/src/pages/api/routes/submissions/[submissionId]/sections/[sectionId]/questions/[questionId]/upload-file.test.tsx
packages/applicant/src/pages/submissions/[submissionId]/sections/[sectionId]/questions/[questionId]/index.page.tsx
packages/applicant/src/pages/submissions/[submissionId]/sections/[sectionId]/questions/[questionId]/index.test.tsx

Adds logic to redirect an applicant back to the summary page after visiting from there

GAP-2049: Conditionally redirect to summary page after file upload 

---

packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/edit/question-content/index.page.tsx
packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/edit/question-content/index.test.tsx

Regression with editing question optionals default values. This PR fixes the default value.
Tested applying for the application in the recording and optional questions worked as expected
https://github.com/cabinetoffice/gap-find-apply-web/assets/101722961/06b74f86-64de-430e-9ac3-107616721208

Fix edit question optional default values

---

packages/gap-web-ui/src/components/question-page/inputs/TextInput.tsx

Following change:
QA (pre-regression):

fix: remove undesired textinput wrapping

---

packages/admin/src/pages/scheme/[schemeId]/editors.getServerSideProps.test.tsx
packages/admin/src/pages/scheme/[schemeId]/editors.getServerSideProps.tsx
packages/admin/src/pages/scheme/[schemeId]/index.module.scss
packages/admin/src/pages/scheme/[schemeId]/index.page.tsx
packages/admin/src/pages/scheme/[schemeId]/index.test.tsx
packages/admin/src/pages/scheme/[schemeId]/manage-editors/index.page.tsx
packages/admin/src/pages/scheme/[schemeId]/manage-editors/index.test.tsx
packages/admin/src/pages/scheme/[schemeId]/view-editors/index.page.tsx
packages/admin/src/pages/scheme/[schemeId]/view-editors/index.test.tsx
packages/admin/src/services/SchemeEditorService.ts
packages/admin/src/services/SchemeService.ts
packages/admin/src/utils/session.ts
packages/gap-web-ui/src/components/summary-list/SummaryList.module.scss
packages/gap-web-ui/src/components/summary-list/SummaryList.tsx
packages/gap-web-ui/src/components/summary-list/index.ts

https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2140
Adds ui for viewing and managing editors

GAP-2140: UI for view & manage editors

---

packages/admin/src/pages/scheme/[schemeId]/advert/[advertId]/survey.page.tsx

[Fix admin satisfaction survey screen](https://technologyprogramme.atlassian.net/browse/TMI2-689)
Removed css from div that was causing an additional two-thirds gov styling spacing issue.

TMI2-689 - removed unnecessary styling from div

---

packages/admin/src/pages/scheme/[schemeId]/[exportId]/index.page.tsx
packages/admin/src/pages/scheme/[schemeId]/[exportId]/index.test.tsx

If there are no submissions available to download then it does not display the download buttons
TMI2-600: https://technologyprogramme.atlassian.net/browse/TMI2-600

TMI2-600: don't show buttons if no submissions to download

---

packages/applicant/src/pages/api/create-submission.page.tsx
packages/applicant/src/pages/api/create-submission.test.tsx

When an advert has an external url with a draft application form, it was trying to send users to this application form. Now a check has been added to send the user to the external application if there is no application form or if the application form has any status other than PUBLISHED
TMI2-697: https://technologyprogramme.atlassian.net/browse/TMI2-697

TMI2-697: handle draft applciation form

---

packages/gap-web-ui/src/components/question-page/inputs/RichText.tsx

The `target="_blank"` attribute is stripped during the process of retrieving the content from contentful, so we're removing this option as in practical terms it does nothing.

remove 'open in new tab' option for links in rich text editor

---

packages/admin/src/pages/super-admin-dashboard/manage-departments/index.page.tsx
packages/admin/src/pages/super-admin-dashboard/manage-departments/index.test.tsx
packages/admin/src/pages/super-admin-dashboard/user/[id]/change-department.page.tsx
packages/admin/src/pages/super-admin-dashboard/user/[id]/change-department.test.tsx

when assigning a role and selecting a department, if a user clicks on `manage departments`, it now carries the new roles over in the query so that the roles and department can be updated
TMI2-702: https://technologyprogramme.atlassian.net/browse/TMI2-702

TMI2-702: error assigning department to user

---

packages/applicant/src/pages/submissions/[submissionId]/sections/[sectionId]/processMultiResponse.test.tsx
packages/applicant/src/pages/submissions/[submissionId]/sections/[sectionId]/processMultiResponse.tsx

Date formats on the submission overview page were not en-UK formatted. 
[Link to story](https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2497)
Introduced a date formatter on the component that outputs date responses on the submission overview page

GAP-2497: Date format in submission overview

---

packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/eligibility-statement.page.tsx
packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/eligibility-statement.test.tsx
packages/admin/src/pages/build-application/[applicationId]/[sectionId]/due-diligence.page.tsx
packages/admin/src/pages/build-application/[applicationId]/[sectionId]/index/getServerSideProps.tsx

Checks application form status. If it's PUBLISHED or REMOVED, admin is redirected to build application dashboard. If the status is not PUBLISHED or REMOVED then admin can edit the application. If the status is REMOVED, the user can only edit custom sections
TMI2-616: https://technologyprogramme.atlassian.net/browse/TMI2-616

TMI2-616: checks application form status before editing

---

packages/admin/src/pages/build-application/[applicationId]/[sectionId]/index/getServerSideProps.tsx
packages/admin/src/pages/build-application/[applicationId]/[sectionId]/index/index.test.tsx
packages/admin/src/pages/build-application/[applicationId]/dashboard.page.tsx
packages/admin/src/pages/build-application/[applicationId]/dashboard.test.tsx
packages/admin/src/pages/scheme/[schemeId]/advert/[advertId]/preview/preview.test.tsx
packages/admin/src/pages/scheme/[schemeId]/advert/[advertId]/section-overview.page.tsx
packages/admin/src/pages/scheme/[schemeId]/advert/[advertId]/section-overview.test.tsx
packages/admin/src/pages/scheme/[schemeId]/advert/[advertId]/summary/summary.test.tsx

Ticket # and link [GAP-2505](https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2505)
Summary of the changes and the related issue. List any dependencies that are required for this change: 
Removes references to /scheme-list in old error pages to now redirect to /dashboard.
[GAP-2505]: https://technologyprogramme.atlassian.net/browse/GAP-2505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GAP-2505: Remove references to 'scheme-list'

---

packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/eligibility-statement.page.tsx
packages/admin/src/pages/build-application/[applicationId]/[sectionId]/due-diligence.page.tsx
packages/admin/src/pages/build-application/[applicationId]/[sectionId]/index/getServerSideProps.tsx
packages/admin/src/pages/build-application/[applicationId]/[sectionId]/index/index.test.tsx

Reverted changes which made essential and required checks sections uneditable while unpublished.
- A user can never edit eligibility or required checks sections but navigating to scheme/{schemeId)/{sectionId) regardless of published state
- A user can edit eligibility statement and due-diligence checks when the application is in draft or removed state
TMI2-616: https://technologyprogramme.atlassian.net/browse/TMI2-616

TMI2-616: reverted changes for editing unpublished application

---

packages/admin/src/pages/super-admin-dashboard/user/[id]/change-department.page.tsx
packages/admin/src/pages/super-admin-dashboard/user/[id]/change-department.test.tsx

The user's role won't be updated until a department is selected to avoid an applicant being promoted to a different role without a department 
TMI2-718: https://technologyprogramme.atlassian.net/browse/TMI2-718

TMI2-718: don't update role if department is undefined

---

packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/unpublished-preview/index.page.tsx
packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/unpublished-preview/index.test.tsx
packages/admin/src/pages/build-application/[applicationId]/preview.page.tsx
packages/admin/src/pages/build-application/[applicationId]/preview.test.tsx
packages/admin/src/pages/build-application/[applicationId]/section-overview.page.tsx
packages/admin/src/pages/build-application/[applicationId]/section-overview.test.tsx
packages/admin/src/services/ApplicationService.ts
packages/admin/src/services/QuestionService.ts
packages/admin/src/utils/applicationSummaryHelper.test.tsx
packages/admin/src/utils/applicationSummaryHelper.ts

Applications always have a v1 shaped `definition`. This definition is expected when we see the initial view of the application (when the admin initially creates it).
When we 'preview' the application we want to render the applicant view (v2 shaped)
This pr adds conditional mapping onto the application summary response so we can render a v2 scheme preview instead of v1 on preview pages.

Map v2 Application form section data

---

packages/admin/src/utils/QuestionPageGetServerSideProps.test.tsx
packages/admin/src/utils/QuestionPageGetServerSideProps.tsx
packages/admin/src/utils/callServiceMethod.ts
packages/admin/src/utils/serviceErrorHelpers.ts

[GAP-2526](https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2526)
related pr: https://github.com/cabinetoffice/gap-find-admin-backend/pull/265/files
[GAP-2526]: https://technologyprogramme.atlassian.net/browse/GAP-2526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Multiple editors - handle editing recently deleted section

---

packages/applicant/src/pages/organisation/index.page.test.tsx
packages/applicant/src/pages/organisation/index.page.tsx

In the table above, the links to add/change details have hidden span tags attached to them in order to aid screen readers by providing better descriptions of what the links are doing. These span tags contained uri components so when the screen reader reached them it would announce "update slash organisation slash name", etc. 
These uri components have been formatted to remove the slashes. There was also some concern over dashes but I have tested these and the screen reader handles them fine so I have left those in place. 
[GAP-1595](https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-1595)
see above.
Please check the …

GAP-1595: Fixing screen reader issue with hidden span tags

---

packages/admin/src/middleware.page.ts
packages/admin/src/middleware.test.ts

Need 307s to preserve post requests and forward them onwards when refreshing JWTs
- (Applicant side already seems to do this locally)

GAP-2596: Refresh JWT via a 307 to preserve POSTs

---

packages/admin/src/pages/scheme/[schemeId]/advert/[advertId]/summary/summary.test.tsx
packages/admin/src/pages/scheme/[schemeId]/advert/[advertId]/summary/summary.testdata.tsx
packages/admin/src/pages/scheme/[schemeId]/advert/[advertId]/summary/summary.tsx
packages/admin/src/testUtils/unitTestHelpers.tsx
packages/admin/src/types/GetSummaryPageContentResponse.ts

if a user sets a grant to publish less than an hour in the past (IE, immediately) during daylight savings time then the "schedule" button will appear as the server operates on UTC and the conversion that determines whether the "schedule" button should appear or not does not take this potential difference in timezones into account. This change adds better handling of absolute date times.
[GAP 2592](https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2592)
see above

fixing daylight savings issue

---

packages/admin/src/middleware.page.ts
packages/admin/src/utils/general.ts
packages/applicant/src/pages/404.page.tsx

[GAP-2587](https://technologyprogramme.atlassian.net/browse/GAP-2587)
if a user was logged in, and tried to access any other subdomain not within his role capabilities, the user service was redirecting the user to its dashboard.
we now implemented logic to redirect the user to a 404/page based on the user role
https://github.com/cabinetoffice/gap-user-service/pull/202
[GAP-2587]: https://technologyprogramme.atlassian.net/browse/GAP-2587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Gap 2587/redirect to404when not allowed on a page

---

packages/admin/src/pages/build-application/[applicationId]/preview.page.tsx

Shifted some code around but actual changes are:
- TS change to correctly make questionId optional
- Logic change to handle the null case where this is no questionId
-  Just displays section title with no link as there is no question to preview
https://github.com/cabinetoffice/gap-find-apply-web/assets/101722961/2a5dfd2e-9d9d-4813-a40f-724ac2441f07

GAP-2621: Fix 500 on empty section previews
