.snyk, packages/admin/.snyk, packages/admin/package.json, packages/applicant/.snyk, packages/applicant/package.json, yarn.lock
downgrade next to fix odd caching errors with page props. to be upgraded to version 13 at a later date.
=> downgrade next to fix caching bugs

.github/workflows/feature.yml, packages/admin/.env.example, packages/admin/src/pages/super-admin-dashboard/Nagivation.tsx, packages/admin/src/pages/super-admin-dashboard/index.page.tsx, packages/admin/src/pages/super-admin-dashboard/types.ts, packages/admin/src/pages/super-admin-dashboard/user/[id]/change-department.page.tsx, packages/admin/src/pages/super-admin-dashboard/user/[id]/change-roles.page.tsx, packages/admin/src/pages/super-admin-dashboard/user/[id]/change-roles.test.tsx, packages/admin/src/pages/super-admin-dashboard/user/[id]/index.page.tsx, packages/admin/src/pages/super-admin-dashboard/utils.ts, packages/admin/src/services/SuperAdminService.ts, packages/admin/src/types/UserDetails.d.ts
- Added find a grant URL to env vars
- Fixed SA dashboard nav links
- Defaulting to paginate to page 0 & 10 items
- Using super generic QuestionPageServerSideProps component thingy
- Change roles now only allows for SA/Admin roles to be enabled/disabled
=> Super admin fixes/cleanup/refactor

packages/admin/src/components/layout/cookie-banner.js, packages/admin/src/pages/build-application/[applicationId]/components/UnpublishSummary.test.tsx, packages/admin/src/pages/build-application/[applicationId]/components/UnpublishSummary.tsx, packages/admin/src/pages/build-application/[applicationId]/dashboard.page.tsx, packages/admin/src/pages/build-application/[applicationId]/unpublish-confirmation.page.tsx, packages/admin/src/pages/scheme/[schemeId]/advert/[advertId]/section-overview.page.tsx, packages/admin/src/pages/scheme/[schemeId]/advert/[advertId]/section-overview.test.tsx, packages/admin/src/utils/related-content-links.ts, packages/applicant/next.config.js, packages/applicant/setupJestMock.js, packages/applicant/src/components/partials/Header.tsx, packages/applicant/src/components/partials/cookie-banner.js, packages/applicant/src/pages/applications/index.page.test.tsx, packages/applicant/src/pages/applications/index.page.tsx, packages/applicant/src/pages/grant-is-closed.page.test.tsx, packages/applicant/src/pages/grant-is-closed.page.tsx, packages/applicant/src/pages/index.page.test.tsx, packages/applicant/src/pages/index.page.tsx, packages/applicant/src/pages/isAdmin.page.tsx, packages/applicant/src/utils/related-content-links.ts, packages/applicant/src/utils/routes.tsx
Removed hardcoded Find a Grant URLs and replaced with .env variable via publicRuntimeConfig
=> GAP-1985 - Removed hardcoded Find a Grant URLs

packages/admin/.env.example, packages/admin/next.config.js, packages/admin/src/pages/dashboard/index.page.tsx, packages/admin/src/pages/dashboard/index.test.tsx, packages/admin/src/utils/general.ts, packages/applicant/.env.example, packages/applicant/next.config.js, packages/applicant/src/pages/api/logout.page.tsx, packages/applicant/src/pages/dashboard/index.page.tsx, packages/applicant/src/utils/general.ts
All instances of enabled/disabled in OneLogin feature flags switched to true/false for consistency.
=> GAP-2052: Inconsistency in OneLogin feature flags

packages/applicant/.env.example, packages/applicant/next.config.js, packages/applicant/src/pages/sign-in-details/index.page.test.tsx, packages/applicant/src/pages/sign-in-details/index.page.tsx
Added serverSideProps to fix issue with cookie handling on page redirect.
=> GAP-1927 - Added serverSideProps to fix issue with cookie handling

packages/applicant/src/pages/index.page.test.tsx, packages/applicant/src/pages/index.page.tsx
https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-1994
=> GAP-1994: View login start page

packages/applicant/src/pages/api/isNewApplicant.page.tsx, packages/applicant/src/pages/isAdmin.page.tsx, packages/applicant/src/utils/routes.tsx
Fixes applicant migration banner not showing by passing query param from isAdmin route down to isNewApplicant and dashboard.
=> fix applicant migration banner

packages/admin/src/pages/api/logout.page.ts
Related PRS:
- https://github.com/cabinetoffice/gap-find-admin-backend/pull/14
- https://github.com/cabinetoffice/gap-user-service/pull/80
=> GAP-1928 - add logout

packages/admin/src/pages/super-admin-dashboard/Navigation.test.tsx, packages/admin/src/pages/super-admin-dashboard/Navigation.tsx, packages/admin/src/pages/super-admin-dashboard/index.page.tsx
Any SuperAdmin will be able to see the Manage API Keys navBarItem in the nav bar to the api-admin app.
=> TMI2-192:remove conditional rendering of the navBar Item

packages/admin/src/pages/super-admin-dashboard/Navigation.tsx
change url, to redirect you to the super admin, api-admin dashboard
=> change manageApiKeys url

packages/admin/src/pages/api/deleteDepartment.page.ts, packages/admin/src/pages/super-admin-dashboard/manage-departments/delete/[id]/error.page.tsx, packages/admin/src/pages/super-admin-dashboard/manage-departments/delete/[id]/index.page.tsx
https://github.com/cabinetoffice/gap-find-apply-web/assets/101722961/a349d778-c582-485e-b0d4-1405511faf08
=> GAP-2127 custom error page for deleting a department with users assigned

packages/applicant/src/pages/sign-in-details/index.page.tsx
https://github.com/cabinetoffice/gap-find-apply-web/assets/107405237/8c487736-79b1-4188-b6cb-bc831f8cfebb
=> GAP-2126 - Adds back link to dashboard on 'Your sign in details' page

packages/admin/src/pages/super-admin-dashboard/user/[id]/index.page.tsx
https://github.com/cabinetoffice/gap-user-service/pull/99
=> GAP-2011 Add None to Departments

packages/applicant/src/pages/_app.page.js
=> fix undefined cookies err

packages/applicant/src/pages/_app.page.js
Attempts to fix a client side error (can't replicate the issue locally) 
=> Fix client side cookies err 

packages/admin/src/middleware.page.ts
Forces a GET req on the redirect to applicant dashboard (when roles are invalid)
=> use get instead of post

packages/applicant/src/pages/index.page.test.tsx, packages/applicant/src/pages/index.page.tsx
=> GAP-2147|copy change for button and update test

yarn.lock
[TMI2-364](https://technologyprogramme.atlassian.net/browse/TMI2-364)
Adds new redirection logic for the user who wants to apply for a grant.
- [√] New feature (non-breaking change which adds functionality).
- [√] Unit Test
[TMI2-364]: https://technologyprogramme.atlassian.net/browse/TMI2-364?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Revert "Bump word-wrap from 1.2.3 to 1.2.4"

packages/admin/src/pages/scheme/[schemeId]/download-submissions.page.tsx
=> GAP-2230: preventing rendering of button if requested=true

packages/applicant/src/pages/applications/index.page.test.tsx, packages/applicant/src/pages/applications/index.page.tsx
Attempts to fix a sandbox only bug on the applicant dashboard.
=> Replaces Next/lInk with an anchor

packages/applicant/src/pages/applications/index.page.test.tsx, packages/applicant/src/pages/applications/index.page.tsx
* use anchor
* amend assertions
=> Deploy bugfix to QA

.github/workflows/admin-ci.yml, .github/workflows/admin-prod-cd.yml, .github/workflows/admin-sandbox-qa-cd.yml, .github/workflows/applicant-ci.yml, .github/workflows/applicant-prod-cd.yml, .github/workflows/applicant-sandbox-qa-cd.yml
- Upgrading ECR login to V2 to prevent docker password leak
- Adding documentation for next cache
- Using restore keys to restore next cache if source files are different, but dependencies are the same
=> Using restore keys to get previous next cache

package.json, packages/applicant/src/pages/api/create-mandatory-question.page.tsx, packages/applicant/src/pages/api/create-mandatory-question.test.tsx, packages/applicant/src/pages/mandatory-questions/[mandatoryQuestionId]/getServerSideProps.test.tsx, packages/applicant/src/pages/mandatory-questions/[mandatoryQuestionId]/getServerSideProps.tsx, packages/applicant/src/pages/mandatory-questions/[mandatoryQuestionId]/organisation-funding-amount.page.tsx, packages/applicant/src/pages/mandatory-questions/[mandatoryQuestionId]/organisation-funding-location.page.tsx, packages/applicant/src/pages/mandatory-questions/[mandatoryQuestionId]/organisation-type.page.tsx, packages/applicant/src/services/GrantMandatoryQuestionService.test.tsx, packages/applicant/src/services/GrantMandatoryQuestionService.ts, packages/gap-web-ui/package.json, yarn.lock
[Ticket # and link](https://technologyprogramme.atlassian.net/browse/TMI2-331)
=> Tmi2 331/mandatory question entry point

packages/applicant/src/utils/callServiceMethod.test.ts, packages/applicant/src/utils/callServiceMethod.ts
add some logic in callServiceMethod to handle special cases of mandatoryQuestion answers
=> add handling for orgType

packages/admin/.snyk, packages/applicant/.snyk, packages/applicant/src/pages/api/mandatory-questions/[mandatoryQuestionId]/create-submission.page.tsx, packages/applicant/src/pages/api/mandatory-questions/[mandatoryQuestionId]/create-submission.test.tsx, packages/applicant/src/pages/api/redirect-from-find.page.test.tsx, packages/applicant/src/pages/mandatory-questions/[mandatoryQuestionId]/external-applications.page.tsx, packages/applicant/src/pages/mandatory-questions/[mandatoryQuestionId]/organisation-summary.page.test.tsx, packages/applicant/src/pages/mandatory-questions/[mandatoryQuestionId]/organisation-summary.page.tsx, packages/applicant/src/services/GrantAdvertService.test.ts, packages/applicant/src/services/GrantAdvertService.tsx, packages/applicant/src/testUtils/unitTestHelpers.tsx, packages/applicant/src/utils/routes.test.tsx, packages/applicant/src/utils/routes.tsx
add action to mandatory question summary page, create redirection page, add  service method, add test coverage
=> add action to mandatory question summary page

packages/applicant/src/pages/mandatory-questions/[mandatoryQuestionId]/external-applications.page.tsx, packages/applicant/src/pages/mandatory-questions/[mandatoryQuestionId]/external-applications.test.tsx
Added external applications page to redirect user to external application form
=> TMI2-357 added external applications pages

packages/applicant/src/pages/submissions/[submissionId]/sections/[sectionId]/index.page.test.tsx, packages/applicant/src/pages/submissions/[submissionId]/sections/[sectionId]/index.page.tsx
Stopping an undefined value being passed in page props as this was causing errors. 
https://technologyprogramme.atlassian.net/jira/software/projects/TMI2/boards/331 
- [ X] Bug fix (non-breaking change which fixes an issue).
- [ X] Unit Test
=> Fixing an error with an undefined value being passed

packages/applicant/src/pages/dashboard/index.page.tsx
=> Adds temp logs to debug

packages/applicant/src/pages/mandatory-questions/[mandatoryQuestionId]/organisation-type.page.tsx, packages/applicant/src/pages/mandatory-questions/[mandatoryQuestionId]/organisation-type.test.tsx, packages/applicant/src/pages/organisation/type.page.tsx, packages/applicant/src/pages/organisation/type.test.tsx
=> TMI2-397 - Changed copy for Organisation type

packages/admin/src/pages/build-application/[applicationId]/components/UnpublishSummary.test.tsx, packages/admin/src/pages/build-application/[applicationId]/components/UnpublishSummary.tsx, packages/admin/src/pages/build-application/[applicationId]/dashboard.page.tsx, packages/admin/src/pages/build-application/[applicationId]/dashboard.test.tsx
[TMI2-437](https://technologyprogramme.atlassian.net/browse/TMI2-437)
fix url in build application dashboard when application is published
[TMI2-437]: https://technologyprogramme.atlassian.net/browse/TMI2-437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix url in build application dashboard when application is published

packages/applicant/src/pages/api/mandatory-questions/[mandatoryQuestionId]/create-submission.page.tsx, packages/applicant/src/pages/api/mandatory-questions/[mandatoryQuestionId]/create-submission.test.tsx, packages/applicant/src/services/GrantMandatoryQuestionService.ts
Added a flag to set the MQ status to complete when the user clicks submit on the front end
https://technologyprogramme.atlassian.net/browse/TMI2-428 
=> TMI2-428: MQ status is never set to complete

packages/applicant/src/pages/api/redirect-from-find.page.test.tsx, packages/applicant/src/pages/api/redirect-from-find.page.tsx
https://technologyprogramme.atlassian.net/browse/TMI2-426
fix redirection to application list instead of submission page
=> fix the redirection

packages/applicant/src/pages/api/redirect-from-find.page.test.tsx, packages/applicant/src/pages/applications/[applicationId]/index.page.test.tsx, packages/applicant/src/pages/applications/[applicationId]/index.page.tsx, packages/applicant/src/pages/applications/index.page.tsx, packages/applicant/src/services/ApplicationService.test.tsx, packages/applicant/src/services/ApplicationService.tsx, packages/applicant/src/services/GrantMandatoryQuestionService.test.tsx, packages/applicant/src/services/GrantMandatoryQuestionService.ts
Ticket # and link](https://technologyprogramme.atlassian.net/browse/TMI2-415)
cover an edge scenario in which the user would try to access a version 2 application, with an old formatted link.
=> Tmi2 415/fix edge scenario for submission

packages/applicant/src/middleware.page.ts, packages/applicant/src/pages/mandatory-questions/start.page.test.tsx, packages/applicant/src/pages/mandatory-questions/start.page.tsx
[Ticket # and link](https://technologyprogramme.atlassian.net/browse/TMI2-439)
cover scenario in which user attempts to access directly the mandatory question start page, after having completed the journey previously
=> fix redirection

packages/admin/src/pages/super-admin-dashboard/user/[id]/change-owner.page.tsx, packages/admin/src/pages/super-admin-dashboard/user/[id]/index.page.tsx, packages/admin/src/pages/super-admin-dashboard/user/[id]/index.test.tsx, packages/admin/src/services/SchemeService.ts, packages/admin/src/services/SuperAdminService.ts
Ticket [GAP-1784](https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-1784)
- Adding schemes owned by the selected user
- Adding missing unit tests
- Adding dummy change ownership page which will be done in another PR
[GAP-1784]: https://technologyprogramme.atlassian.net/browse/GAP-1784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GAP-1784: Transfer ownership

packages/admin/src/pages/api/downloadDueDiligenceChecks.page.ts, packages/admin/src/pages/api/downloadDueDiligenceChecks.test.ts, packages/admin/src/pages/scheme/[schemeId]/index.page.tsx, packages/admin/src/pages/scheme/[schemeId]/index.test.tsx, packages/admin/src/pages/scheme/[schemeId]/manage-due-diligence-checks.page.tsx, packages/admin/src/pages/scheme/[schemeId]/manage-due-diligence-checks.test.tsx, packages/admin/src/pages/scheme/components/SchemeApplications.test.tsx, packages/admin/src/pages/scheme/components/SchemeApplications.tsx, packages/admin/src/services/MandatoryQuestionsService.test.ts, packages/admin/src/services/MandatoryQuestionsService.ts, packages/applicant/src/pages/api/mandatory-questions/[mandatoryQuestionId]/create-submission.page.tsx, packages/applicant/src/pages/api/mandatory-questions/[mandatoryQuestionId]/create-submission.test.tsx
- adds manage due diligence page
- adds functionality to download due diligence info from mandatory questions
=> TMI2-335 adds mandatory questions download

packages/applicant/src/pages/mandatory-questions/[mandatoryQuestionId]/organisation-funding-location.page.tsx, packages/applicant/src/pages/mandatory-questions/[mandatoryQuestionId]/organisation-funding-location.test.tsx
=> TMI2-328 - Updated funding locations list

packages/applicant/.env.example, packages/applicant/src/components/partials/Header.tsx, packages/applicant/src/components/partials/Layout.test.tsx, packages/applicant/src/components/partials/Layout.tsx, packages/applicant/src/pages/_app.page.js
=> hide nav when OL disabled

packages/admin/src/pages/super-admin-dashboard/user/[id]/index.page.tsx, packages/admin/src/pages/super-admin-dashboard/user/[id]/index.test.tsx
Worked locally as ids happened to match up, but they dont in sandbox! Fixing to query correct tables
=> GAP-2290: Fix transfer ownership

packages/admin/src/pages/super-admin-dashboard/user/[id]/schemes/[schemeId]/change-owner.page.tsx, packages/admin/src/pages/super-admin-dashboard/user/[id]/schemes/[schemeId]/change-owner.test.tsx, packages/admin/src/pages/super-admin-dashboard/user/[id]/schemes/[schemeId]/confirm-change-owner.page.tsx, packages/admin/src/services/UserService.ts
Ticket # and link GAP-1784
Fixes missing ac.
=> GAP-1784: Stops  superadmin assigning grant to current owner

packages/admin/src/pages/scheme/[schemeId]/index.page.tsx, packages/admin/src/pages/scheme/[schemeId]/index.test.tsx, packages/admin/src/pages/scheme/[schemeId]/manage-due-diligence-checks.page.tsx, packages/admin/src/pages/scheme/[schemeId]/manage-due-diligence-checks.test.tsx, packages/admin/src/pages/scheme/components/SchemeApplications.test.tsx, packages/admin/src/pages/scheme/components/SchemeApplications.tsx
=> only display due diligence btn for V2 (#157)

packages/admin/src/pages/scheme/[schemeId]/manage-due-diligence-checks.page.tsx, packages/admin/src/pages/scheme/[schemeId]/manage-due-diligence-checks.test.tsx, packages/admin/src/services/SchemeService.test.ts, packages/admin/src/services/SchemeService.ts, packages/admin/src/services/SectionService.test.ts
=> TMI2-390 - Login to Spotlight from DD checks page

packages/applicant/src/pages/mandatory-questions/[mandatoryQuestionId]/organisation-funding-amount.page.tsx
=> TMI2-332 - Removed styling div

packages/applicant/src/pages/mandatory-questions/[mandatoryQuestionId]/getServerSideProps.test.tsx, packages/applicant/src/pages/mandatory-questions/[mandatoryQuestionId]/getServerSideProps.tsx, packages/applicant/src/pages/mandatory-questions/[mandatoryQuestionId]/organisation-summary.page.tsx, packages/applicant/src/pages/mandatory-questions/[mandatoryQuestionId]/organisation-type.page.tsx, packages/applicant/src/pages/mandatory-questions/[mandatoryQuestionId]/organisation-type.test.tsx, packages/applicant/src/pages/submissions/[submissionId]/sections/[sectionId]/index.page.test.tsx, packages/applicant/src/pages/submissions/[submissionId]/sections/[sectionId]/index.page.tsx, packages/applicant/src/utils/routes.tsx
[GAP-2249](https://technologyprogramme.atlassian.net/browse/GAP-2249)
implement change for individual copy, get section title working
Related PRs:
https://github.com/cabinetoffice/gap-find-applicant-backend/pull/58
[GAP-2249]: https://technologyprogramme.atlassian.net/browse/GAP-2249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GAP-2249: Conditional Logic - Changes to submission for applicant types

packages/applicant/src/pages/mandatory-questions/[mandatoryQuestionId]/organisation-summary.page.tsx, packages/applicant/src/pages/mandatory-questions/start.page.tsx
[GAP-2254 (Update content for journeys)](https://technologyprogramme.atlassian.net/browse/GAP-2254)
Images of the changes:
=> Updated content for start page and summary page.

packages/applicant/src/pages/organisation/address.page.tsx, packages/applicant/src/pages/organisation/address.test.tsx, packages/applicant/src/pages/organisation/getServerSideProps.test.tsx, packages/applicant/src/pages/organisation/getServerSideProps.tsx, packages/applicant/src/pages/organisation/name.page.tsx, packages/applicant/src/pages/organisation/name.test.tsx
Changes copy on name & address edit pages for individual applicants
https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2307
=> GAP-2307: Edit name and address in org profile as an individual

packages/admin/src/pages/scheme/[schemeId]/index.page.tsx, packages/admin/src/pages/scheme/[schemeId]/index.test.tsx
https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2302
=> Hide due diligence section when no advert and no application attached to scheme

packages/admin/src/pages/scheme/[schemeId]/manage-due-diligence-checks.page.tsx, packages/admin/src/pages/scheme/[schemeId]/manage-due-diligence-checks.test.tsx
=> TMI2-449 - Update copy on external application due diligence page

packages/admin/src/components/custom-link/CustomLink.tsx, packages/admin/src/pages/api/signed-url.page.ts, packages/admin/src/pages/api/signed-urls.page.ts, packages/admin/src/pages/index.page.tsx, packages/admin/src/pages/scheme/[schemeId]/[exportId].page.tsx, packages/admin/src/services/SubmissionsService.ts
https://technologyprogramme.atlassian.net/browse/GAP-2221
Generates presigned url for submission export files on demand when the user clicks a download link.
=> generate doc export url on demand

packages/applicant/src/middleware.page.ts, packages/applicant/src/middleware.test.ts
[Ticket 2315
](https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2315)
- Middleware refresh token logic was stripping query params which breaks some flows
=> GAP-2315: Fix middleware refresh token stripping query params

packages/admin/src/components/notification-banner/SpotlightMessage.tsx, packages/admin/src/pages/scheme/[schemeId]/manage-due-diligence-checks.test.tsx
=> TMI2-420 API error text fix

packages/admin/.snyk, packages/applicant/.snyk, packages/applicant/src/pages/api/redirect-from-find.page.test.tsx, packages/applicant/src/pages/api/redirect-from-find.page.tsx, packages/applicant/src/services/GrantMandatoryQuestionService.ts
=> fix logic to allow redirection on completed mq for external v2 adverts.

packages/admin/src/pages/scheme/[schemeId]/manage-due-diligence-checks.page.tsx, packages/admin/src/pages/scheme/[schemeId]/manage-due-diligence-checks.test.tsx
Copy change for the due diligence downloads link.
[TMI2-481 - Download link for external applications copy is incorrect](https://technologyprogramme.atlassian.net/browse/TMI2-481)
=> TMI2-481 - Download link for external applications copy is incorrect

packages/applicant/src/pages/api/submissions/[submissionId]/sections/[sectionId]/questions/[questionId]/upload-file.page.tsx
=> TMI2-494/ fix bug in upload question

packages/applicant/cypress/integration/applicant/organisation.spec.js, packages/applicant/src/pages/organisation/index.page.test.tsx, packages/applicant/src/pages/organisation/index.page.tsx
=> GAP-2334 | fix bad capitalisation

packages/admin/src/pages/api/manage-due-diligence/v2/internal/downloadSpotlightSubmissionsChecks.page.ts
=> Adds debug log

packages/admin/src/pages/build-application/[applicationId]/dashboard.page.tsx
['Find a grant' Hyperlink opens in the same tab](https://technologyprogramme.atlassian.net/browse/TD-162)
Adds relevant CSS to allow the anchor tag to open the Find a grant link in a new tab.
=> TMI2-519 - Changed Find a grant hyperlink to open in a new tab

packages/admin/package.json, yarn.lock
Adds missing dependency to fix pipeline failure 💀
=> TMI2-521 - Added rich-text-from-markdown

packages/applicant/src/pages/submissions/[submissionId]/sections.page.test.tsx, packages/applicant/src/pages/submissions/[submissionId]/sections.page.tsx, packages/applicant/src/pages/submissions/[submissionId]/submit.page.test.tsx, packages/applicant/src/pages/submissions/[submissionId]/submit.page.tsx, packages/applicant/src/pages/submissions/[submissionId]/summary.page.test.tsx, packages/applicant/src/pages/submissions/[submissionId]/summary.page.tsx, packages/applicant/src/services/SubmissionService.tsx, packages/applicant/src/utils/routes.tsx
[GAP-1819](https://technologyprogramme.atlassian.net/browse/GAP-1819)
Adding summary page between submission sections page and submission submit.
I've added placeholder links for Change and download but they're properly implemented in https://github.com/cabinetoffice/gap-find-apply-web/pull/234. Also added some work for viewing completed submission but not hooked up.
Video in ticket
[GAP-1819]: https://technologyprogramme.atlassian.net/browse/GAP-1819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GAP-1819: Submission Summary

packages/applicant/src/pages/applications/index.page.tsx
=> GAP-2095 | fix link and add way to display GRANT_CLOSED without BE work

packages/admin/src/pages/scheme/[schemeId]/advert/[advertId]/summary/summary.tsx
=> fixes form validation by removing hard coded time value

packages/admin/src/pages/scheme/[schemeId]/advert/[advertId]/summary/components/Date.tsx, packages/gap-web-ui/src/components/question-page/inputs/DateTimeInput.test.tsx, packages/gap-web-ui/src/components/question-page/inputs/DateTimeInput.tsx
=> adds default values to the time drop down

packages/admin/src/pages/super-admin-dashboard/types.ts, packages/admin/src/pages/super-admin-dashboard/user/[id]/change-department.page.tsx, packages/admin/src/pages/super-admin-dashboard/user/[id]/change-department.test.tsx, packages/admin/src/pages/super-admin-dashboard/user/[id]/change-roles.page.tsx, packages/admin/src/pages/super-admin-dashboard/user/[id]/change-roles.test.tsx
GAP-2384: https://technologyprogramme.atlassian.net/browse/GAP-2384 
Bug fix to prevent a department not being selected on an Admin role when the 'Back' button is pressed (after selecting a role)
Screen recording showing bug fix
https://github.com/cabinetoffice/gap-find-apply-web/assets/145372589/bfe767bb-b51a-4c44-ae51-bdba21234005
=> GAP 2384 No department being selected bug

packages/applicant/src/pages/submissions/[submissionId]/equality-and-diversity/[grantBeneficiaryId]/age.page.test.tsx, packages/applicant/src/pages/submissions/[submissionId]/equality-and-diversity/[grantBeneficiaryId]/age.page.tsx, packages/applicant/src/pages/submissions/[submissionId]/equality-and-diversity/[grantBeneficiaryId]/sexual-orientation.page.test.tsx, packages/applicant/src/pages/submissions/[submissionId]/equality-and-diversity/[grantBeneficiaryId]/sexual-orientation.page.tsx
When a user went to change an answer with checkboxes and wanted to uncheck all the boxes, the responses weren't being saved because no call was being made to the backend, now a call is always made to the backend
TMI2-564: https://technologyprogramme.atlassian.net/browse/TMI2-564
=> TMI2-564: E&D - unable to remove response

packages/applicant/src/utils/postQuestion.ts
=> GAP-2096 | add logging and optional chaining for error in postQuestion

packages/applicant/src/pages/api/routes/submissions/[submissionId]/download-summary.page.tsx, packages/applicant/src/pages/api/routes/submissions/[submissionId]/download-summary.test.tsx, packages/applicant/src/pages/submissions/[submissionId]/summary.page.test.tsx, packages/applicant/src/pages/submissions/[submissionId]/summary.page.tsx
https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2388
Related pr: https://github.com/cabinetoffice/gap-find-applicant-backend/pull/95
=> GAP-2388: download zip

packages/applicant/src/pages/mandatory-questions/[mandatoryQuestionId]/getServerSideProps.test.tsx, packages/applicant/src/pages/mandatory-questions/[mandatoryQuestionId]/getServerSideProps.tsx, packages/applicant/src/pages/submissions/[submissionId]/sections.page.test.tsx, packages/applicant/src/pages/submissions/[submissionId]/sections.page.tsx, packages/applicant/src/testUtils/unitTestHelpers.tsx
=> csrf fixes

.github/workflows/admin-prod-cd.yml, .github/workflows/admin-sandbox-qa-cd.yml, .github/workflows/applicant-prod-cd.yml, .github/workflows/applicant-sandbox-qa-cd.yml, Dockerfile
=> copy all packages in dockerfile

Dockerfile
=> ensure same version of yarn used in Dockefile as elsewhere

Dockerfile
=> fix yarn install in dockerfile

packages/admin/package.json, packages/applicant/package.json, yarn.lock
=> add body-parser to admin package.json

packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/edit/question-options.page.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/edit/question-options.test.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/question-options.page.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/question-options.test.tsx, packages/admin/src/utils/QuestionPageGetServerSideProps.tsx
=> fix multi-select and QuestionPageGetServerSideProps

.github/workflows/admin-prod-cd.yml, .github/workflows/admin-sandbox-qa-cd.yml, .github/workflows/applicant-prod-cd.yml, .github/workflows/applicant-sandbox-qa-cd.yml
PIpeline changes - checklist not required
=> Tmi2 532/run actions as aws role

packages/admin/src/pages/super-admin-dashboard/types.ts, packages/admin/src/pages/super-admin-dashboard/user/[id]/change-department.page.tsx, packages/admin/src/pages/super-admin-dashboard/user/[id]/change-department.test.tsx, packages/admin/src/services/SuperAdminService.ts, packages/admin/src/utils/QuestionPageGetServerSidePropsTypes.ts
=> fix type of department

packages/admin/src/pages/build-application/[applicationId]/[sectionId]/edit-title.page.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/edit-title.test.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/index.page.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/index.test.tsx, packages/admin/src/services/SectionService.ts, packages/admin/src/types/Section.d.ts, packages/admin/src/utils/session.ts
Adds ui for an admin to change a section title
[GAP-2103](https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2103)
Related pr: https://github.com/cabinetoffice/gap-find-admin-backend/pull/162
[GAP-2103]: https://technologyprogramme.atlassian.net/browse/GAP-2103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GAP-2103 - Edit section title

packages/admin/src/pages/build-application/[applicationId]/[sectionId]/delete-confirmation.page.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/index.page.tsx, packages/admin/src/pages/build-application/[applicationId]/components/Sections.test.tsx, packages/admin/src/pages/build-application/[applicationId]/components/Sections.tsx, packages/admin/src/pages/build-application/[applicationId]/dashboard.page.tsx, packages/gap-web-ui/src/components/table/Table.tsx
Small UX / accessibility fixes with application builder recent changes
=> Gap 2102 ux improvements

packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/delete-confirmation.page.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/edit/question-content.page.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/edit/question-content.test.tsx
=> Minor UI updates following figma changes

packages/admin/src/pages/build-application/[applicationId]/survey.page.tsx, packages/admin/src/pages/scheme/[schemeId]/advert/[advertId]/survey.page.tsx, packages/admin/src/services/SatisfactionSurveyService.ts
https://technologyprogramme.atlassian.net/browse/TMI2-549
Removes the default radio option on the feedback survey.
=> TMI2-549 - Removing default radio option from survey

packages/applicant/src/pages/submissions/[submissionId]/summary.page.test.tsx, packages/applicant/src/pages/submissions/[submissionId]/summary.page.tsx
Small fix to add full stop to banner in summary page (for closed grants)
=> Adding fullstop to text in Important banner.

packages/admin/src/services/SatisfactionSurveyService.test.ts
=> TMI2-549 - Fix for broken unit test

packages/applicant/src/pages/submissions/[submissionId]/summary.page.tsx
Adds correct copy for summary page for CLOSED GRANT application forms.
=> Small fix to correct title copy for CLOSED grant summary page

packages/applicant/src/pages/api/routes/submissions/[submissionId]/sections/[sectionId]/questions/[questionId]/upload-file.page.tsx, packages/applicant/src/pages/api/routes/submissions/[submissionId]/sections/[sectionId]/questions/[questionId]/upload-file.test.tsx
=> Fix redirect case in upload-file

packages/admin/src/pages/build-application/[applicationId]/[sectionId]/question-type/index.page.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/question-type/index.test.tsx
=> Minor copy update in app builder

packages/admin/src/pages/build-application/[applicationId]/[sectionId]/components/QuestionTypeHint.module.scss, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/components/QuestionTypeHint.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/question-type/index.page.tsx
=> Fix responsive styles

packages/applicant/src/pages/organisation/index.page.test.tsx, packages/applicant/src/pages/organisation/index.page.tsx
=> TMI2-628 - removes charity commission and companies house fields from local authority on org profile page

packages/applicant/src/pages/mandatory-questions/[mandatoryQuestionId]/getServerSideProps.test.tsx, packages/applicant/src/pages/mandatory-questions/[mandatoryQuestionId]/getServerSideProps.tsx
=> TMI2-628 - removes charity commission and companies house number from local authority questions

packages/admin/src/enums/ExportStatus.ts, packages/admin/src/pages/scheme/[schemeId]/download-submissions.page.tsx
This is just a temporary fix for handling the failed status. This will eventually change with the error in export work
https://technologyprogramme.atlassian.net/browse/TMI2-602
=> TMI2-602: handles failed status

packages/applicant/package.json
=> fix request/response logging

packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/edit/question-content/getServerSideProps.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/edit/question-content/index.page.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/edit/question-options.getServerSideProps.test.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/edit/question-options.getServerSideProps.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/edit/question-options.page.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/question-options.page.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/question-type/add-word-count.page.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/question-type/add-word-count.test.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/question-type/index.getServerSideProps.test.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/question-type/index.getServerSideProps.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/question-type/index.page.tsx, packages/admin/src/services/QuestionService.ts, packages/admin/src/services/SessionService.ts, packages/admin/src/types/ApplicationForm.d.ts, packages/admin/src/types/QuestionSummary.d.ts, packages/admin/src/utils/QuestionPageGetServerSideProps.test.tsx, packages/admin/src/utils/QuestionPageGetServerSideProps.tsx, packages/admin/src/utils/QuestionPageGetServerSidePropsTypes.ts, packages/admin/src/utils/general.test.ts, packages/admin/src/utils/general.ts
[GAP-2105](https://technologyprogramme.atlassian.net/browse/GAP-2105)
https://github.com/cabinetoffice/gap-find-admin-backend/pull/199
[GAP-2105]: https://technologyprogramme.atlassian.net/browse/GAP-2105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GAP-2105 | Change Question Type for Application Builder

packages/admin/src/pages/build-application/[applicationId]/[sectionId]/question-type/index.getServerSideProps.tsx, packages/admin/src/services/QuestionService.ts
Bugfix, as title. Please ignore my confusion at the start of the video, I thought I was on the section page already.
https://github.com/cabinetoffice/gap-find-apply-web/assets/135321532/20b7b7a7-7e16-4584-a679-744d09ed9f31
=> fix: can add new questions to application form

packages/applicant/src/pages/submissions/[submissionId]/summary.page.tsx
=> check submission not submitted before displaying grant closed banner

packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/preview-input-switch.test.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/preview-input-switch.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/preview.module.scss, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/preview.page.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/preview.test.tsx
=> restore deleted preview page

packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/edit/question-options.getServerSideProps.tsx
https://github.com/cabinetoffice/gap-find-apply-web/assets/135321532/ba9d8141-7e3f-4b5c-b114-88a9ba508c74
=> fix: cannot change from non multi question to multi

packages/admin/src/pages/scheme/[schemeId]/[exportId]/index.page.tsx, packages/admin/src/pages/scheme/[schemeId]/[exportId]/index.test.tsx, packages/admin/src/pages/scheme/[schemeId]/[exportId]/view/QuestionRow.component.tsx, packages/admin/src/pages/scheme/[schemeId]/[exportId]/view/QuestionRow.test.tsx, packages/admin/src/pages/scheme/[schemeId]/[exportId]/view/[submissionId].page.tsx, packages/admin/src/pages/scheme/[schemeId]/[exportId]/view/[submissionId].test.tsx, packages/admin/src/services/ExportService.ts, packages/admin/src/services/SubmissionsService.test.ts, packages/admin/src/services/SubmissionsService.ts, packages/admin/src/types/SubmissionSummary.d.ts
[View summary of applications unable to download - error path](https://technologyprogramme.atlassian.net/jira/software/projects/TMI2/boards/331?selectedIssue=TMI2-605)
Added link to View individual submissions from scheme > [schemeId] > [exportId] > index.page
Added a read-only summary for individual submissions.
The download attachments option on the page design is outside the scope of this ticket and is currently absent.
https://github.com/cabinetoffice/gap-find-apply-web/assets/107405237/d6a21a09-333e-4a3c-869a-c428ca095fe8
=> TMI2-605 -  View submission summary (error path)

packages/admin/src/pages/scheme/[schemeId]/[exportId]/view/[submissionId].page.tsx, packages/admin/src/pages/scheme/[schemeId]/[exportId]/view/[submissionId].test.tsx
[Download attachments - error path](https://technologyprogramme.atlassian.net/jira/software/projects/TMI2/boards/331?selectedIssue=TMI2-669)
=> TMI2-669 - download attachments error path

packages/admin/src/pages/scheme/[schemeId]/manage-editors/index.page.tsx
Fixes banner width on manage-editors page
=> GAP-2137: Fix banner width

packages/admin/src/pages/scheme/components/BuildAdvert.test.tsx, packages/admin/src/pages/scheme/components/BuildAdvertContentHelper.tsx, packages/admin/src/services/AdvertPageService.d.ts
related pr: https://github.com/cabinetoffice/gap-find-admin-backend/pull/230
Additional AC added with this ticket https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2432
(use created by when we have an invalid 'legacy' advert.)
=> Handle last updated edge cases

packages/admin/src/pages/scheme/components/BuildAdvert.test.tsx, packages/admin/src/pages/scheme/components/BuildAdvertContentHelper.tsx
=> Use 12 hour time on advert lastUpdated

packages/admin/src/pages/build-application/[applicationId]/survey.page.tsx, packages/admin/src/pages/scheme/[schemeId]/advert/[advertId]/survey.page.tsx
[Fix admin satisfaction survey screen](https://technologyprogramme.atlassian.net/jira/software/projects/TMI2/boards/331?selectedIssue=TMI2-689)
=> TMI2-689 - Admin satisfaction survey better fix

packages/admin/src/pages/scheme/[schemeId]/index.page.tsx
Fixes an issue where email address for application forms was overwritten by placeholder value when advert was not created.
=> GAP:2433 Fix bad reassignment of email

packages/admin/src/pages/scheme/components/BuildAdvert.test.tsx, packages/admin/src/pages/scheme/components/BuildAdvertContentHelper.tsx
=> update scheduled advert copy

packages/admin/src/pages/scheme/[schemeId]/advert/[advertId]/survey.page.tsx
=> TMI2-689 - adds missing css to div

packages/applicant/src/pages/api/create-submission.page.tsx
=> TMI2-697: checks if application is published

packages/applicant/src/pages/api/create-submission.page.tsx, packages/applicant/src/pages/api/create-submission.test.tsx
Hotfix release 9.1
https://technologyprogramme.atlassian.net/browse/TMI2-697
=> HOTFIX Release 9.1

packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/edit/question-content/getServerSideProps.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/edit/question-content/index.page.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/edit/question-options.getServerSideProps.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/edit/question-options.page.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/eligibility-statement.page.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/eligibility-statement.test.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/question-type/add-word-count.page.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/question-type/add-word-count.test.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/question-type/index.getServerSideProps.test.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/question-type/index.getServerSideProps.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/question-type/index.page.tsx, packages/admin/src/services/QuestionService.ts
Covers [GAP-2458](https://technologyprogramme.atlassian.net/browse/GAP-2458), [GAP-2456](https://technologyprogramme.atlassian.net/browse/GAP-2456) and [GAP-2459](https://technologyprogramme.atlassian.net/browse/GAP-2459)
Multiple Editors - edit question title, type, options, max words, eligibility
https://github.com/cabinetoffice/gap-find-admin-backend/pull/238
Video in [GAP-2458 ticket](https://technologyprogramme.atlassian.net/browse/GAP-2458)
[GAP-2458]: https://technologyprogramme.atlassian.net/browse/GAP-2458?atlOrigin=eyJpIj …
=> GAP-2458 | GAP-2459 | GAP-2456: Multiple Editors - edit question title, type, options, max words, eligibility

packages/admin/src/pages/scheme/components/BuildAdvertContentHelper.tsx
=> Adds check for deleted user

packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/delete-confirmation.page.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/delete-confirmation.test.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/edit/question-content/getServerSideProps.test.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/edit/question-content/getServerSideProps.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/edit/question-content/index.page.tsx, packages/admin/src/services/QuestionService.test.ts, packages/admin/src/services/QuestionService.ts
[GAP-2461](https://technologyprogramme.atlassian.net/browse/GAP-2461)
Prevent editors from deleting question if version is outdated
https://github.com/cabinetoffice/gap-find-admin-backend/pull/240
[GAP-2461]: https://technologyprogramme.atlassian.net/browse/GAP-2461?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GAP-2461: Multiple Editors - delete question

packages/admin/src/pages/build-application/[applicationId]/publish-success.page.tsx, packages/admin/src/pages/build-application/[applicationId]/publish-success.test.tsx, packages/admin/src/pages/build-application/[applicationId]/survey.page.tsx
[TMI2-674 - Add admin satisfaction survey when user clicks "Add a new grant"](https://technologyprogramme.atlassian.net/browse/TMI2-674)
Adds redirect to the satisfaction survey page when adding a new grant.
Adds logic on the survey page to redirect the user upon survey submission to the appropriate link based on query params.
=> TMI2-674 - Add admin satisfaction survey when user clicks "Add a new grant"

packages/admin/src/pages/build-application/[applicationId]/components/Sections.test.tsx, packages/admin/src/pages/build-application/[applicationId]/components/Sections.tsx, packages/admin/src/pages/build-application/[applicationId]/dashboard.page.tsx, packages/admin/src/pages/build-application/[applicationId]/dashboard.test.tsx, packages/admin/src/services/ApplicationService.test.ts, packages/admin/src/services/ApplicationService.ts
[GAP-2462](https://technologyprogramme.atlassian.net/browse/GAP-2462)
https://github.com/cabinetoffice/gap-find-admin-backend/pull/241
[GAP-2462]: https://technologyprogramme.atlassian.net/browse/GAP-2462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GAP-2462: Multiple Editors section reorder

packages/admin/src/pages/build-application/[applicationId]/[sectionId]/index.page.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/index/getServerSideProps.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/index/index.test.tsx, packages/admin/src/services/ApplicationService.test.ts, packages/admin/src/services/ApplicationService.ts
[GAP-2463](https://technologyprogramme.atlassian.net/browse/GAP-2463)
https://github.com/cabinetoffice/gap-find-admin-backend/pull/242
[GAP-2463]: https://technologyprogramme.atlassian.net/browse/GAP-2463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GAP-2463: Multiple Editors question reorder

packages/admin/src/pages/build-application/[applicationId]/error-multiple-editors.page.tsx, packages/admin/src/pages/build-application/[applicationId]/error-multiple-editors.test.tsx, packages/admin/src/utils/callServiceMethod.test.ts, packages/admin/src/utils/callServiceMethod.ts, packages/admin/src/utils/serviceErrorHelper.test.ts, packages/admin/src/utils/serviceErrorHelpers.ts
Handle case where editor adds a question to a deleted section
- Edits ErrorMultipleEditorsPage to accept a conditional error message passed via query string
- Passes a custom error message when conflict exception reads `MULTIPLE_EDITORS_SECTION_DELETED
[GAP-2455](https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2455)
related pr: [backend](https://github.com/cabinetoffice/gap-find-admin-backend/pull/245)
(video demo is in jira)
[GAP-2455]: https://technologyprogramme.atlassian.net/browse/GAP-2455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GAP-2455 | Handle editor adding question to a deleted section 

packages/admin/src/pages/new-scheme/name.page.tsx, packages/admin/src/pages/new-scheme/name.test.tsx, packages/admin/src/pages/new-scheme/summary.page.tsx, packages/admin/src/pages/new-scheme/summary.test.tsx, packages/admin/src/services/SchemeService.test.ts, packages/admin/src/services/SchemeService.ts
=> amend names of shcheme and advert name fields

packages/admin/src/pages/build-application/[applicationId]/[sectionId]/index.page.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/index/QuestionRowActionComponent.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/index/index.module.scss
Ticket [GAP-2502](https://technologyprogramme.atlassian.net/browse/GAP-2502)
- Wrapping up, down & edit buttons more neatly
[GAP-2502]: https://technologyprogramme.atlassian.net/browse/GAP-2502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GAP-2502: Wrapping edit section questions tables final column better

packages/admin/src/pages/scheme/[schemeId]/advert/name.page.tsx, packages/admin/src/services/AdvertPageService.test.ts, packages/admin/src/services/AdvertPageService.ts
=> fix advert name

packages/admin/src/middleware.page.ts, packages/admin/src/middleware.test.ts
When logged out, should redirect user to submissions download page after logging in
TMI2-720: https://technologyprogramme.atlassian.net/browse/TMI2-720
=> TMI2-720: view submissions link when logged out

packages/admin/src/middleware.page.ts
Fixed the submission download pattern
TMI2-720: https://technologyprogramme.atlassian.net/browse/TMI2-720
=> TMI2-720: redirect to submission download after login

packages/admin/src/pages/api/applications/[applicationId]/download-summary.page.tsx, packages/admin/src/pages/api/applications/[applicationId]/download-summary.test.tsx
[GAP-2517](https://technologyprogramme.atlassian.net/browse/GAP-2517)
[GAP-2517]: https://technologyprogramme.atlassian.net/browse/GAP-2517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GAP-2517: put application name into the downloaded application form summary odt

packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/preview.page.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/preview.test.tsx
https://technologyprogramme.atlassian.net/browse/TMI2-728
Updates the question preview on published applications so that the UI preview is consistent with in-progress applications.
=> TMI2-728 - Application preview update

packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/preview-input-switch.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/preview.page.tsx
Added hint text and removed space
TMI2-728: https://technologyprogramme.atlassian.net/browse/TMI2-728
=> TMI2-728: added hint text and removed space

packages/admin/src/pages/build-application/[applicationId]/dashboard.page.tsx, packages/admin/src/pages/build-application/[applicationId]/dashboard.test.tsx, packages/admin/src/pages/build-application/[applicationId]/preview.module.scss, packages/admin/src/pages/build-application/[applicationId]/preview.page.tsx, packages/admin/src/pages/build-application/[applicationId]/preview.test.tsx, packages/admin/src/services/ApplicationService.ts, packages/admin/src/types/Scheme.d.ts, packages/applicant/src/pages/submissions/[submissionId]/sections.page.tsx
[GAP-2437](https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2437)
Adds UI for preview application form:
[GAP-2437]: https://technologyprogramme.atlassian.net/browse/GAP-2437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GAP-2437 - Add preview application form ui

packages/admin/src/pages/scheme/[schemeId]/manage-editors/index.page.tsx
[GAP-2524](https://technologyprogramme.atlassian.net/browse/GAP-2524)
[GAP-2524]: https://technologyprogramme.atlassian.net/browse/GAP-2524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GAP-2524 | change manage editors support email link to mailto

packages/applicant/src/components/partials/Header.tsx
=> use anchor tag for logout

packages/admin/src/pages/new-scheme/summary.page.tsx, packages/admin/src/pages/new-scheme/summary.test.tsx, packages/admin/src/services/SchemeService.ts
[GAP-2519](https://technologyprogramme.atlassian.net/browse/GAP-2519)
[GAP-2519]: https://technologyprogramme.atlassian.net/browse/GAP-2519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GAP-2519 | go to scheme details after creation

packages/admin/package.json, yarn.lock
[TMI2-733](https://technologyprogramme.atlassian.net/browse/TMI2-733?atlOrigin=eyJpIjoiNjlkNGIwMzJiYzU4NDU0OWIwNTZiYTdiMGNhYjVhYTciLCJwIjoiaiJ9)
Fixing an issue encountered with this feature where a 500 error is given on the search-result preview page.
This change adds the dependency `moment-timezone` to admin-backend in an attempt to fix the issue.
=> FIX TMI2-773: Advert Preview

packages/admin/src/middleware.page.ts, packages/admin/src/middleware.test.ts, packages/applicant/src/middleware.page.ts
=> only call csrf middleware once

.eslintrc.js, packages/admin/src/pages/scheme/[schemeId]/advert/[advertId]/summary/summary.tsx
=> rm more console logs

packages/applicant/src/pages/api/create-submission.page.tsx, packages/applicant/src/pages/api/create-submission.test.tsx, packages/applicant/src/pages/mandatory-questions/start.page.test.tsx, packages/applicant/src/pages/mandatory-questions/start.page.tsx, packages/applicant/src/services/GrantSchemeService.test.ts, packages/applicant/src/services/GrantSchemeService.ts
=> GAP-2537:fix logic to handle applications with no adverts

packages/applicant/src/middleware.page.ts, packages/applicant/src/utils/csrfMiddleware/index.ts
=> temporarily fix middleware

packages/admin/src/utils/csrfMiddleware/utils.ts, packages/applicant/src/utils/csrfMiddleware/utils.ts
=> fix binary conversion

packages/applicant/src/utils/csrfMiddleware/secret.ts
=> remove https from host domain

packages/applicant/src/pages/api/csrf.page.tsx, packages/applicant/src/pages/api/csrf.test.tsx, packages/applicant/src/utils/csrfMiddleware/secret.ts
=> add explanatory comments and improve security

packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/edit/question-options.getServerSideProps.test.tsx, packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/edit/question-options.getServerSideProps.tsx, packages/admin/src/types/ApplicationForm.d.ts, packages/admin/src/types/QuestionSummary.d.ts
https://technologyprogramme.atlassian.net/browse/GAP-2620
Handling optional/mandatory value in questions with multi-choice options correctly, using value from previous page rather than from database
=> Gap 2620/fixing validation issues

packages/admin/src/pages/build-application/[applicationId]/[sectionId]/[questionId]/edit/question-options.getServerSideProps.tsx
#GAP-2656
https://technologyprogramme.atlassian.net/browse/GAP-2656
=> Fixing change question type to multi choice

packages/applicant/src/pages/mandatory-questions/[mandatoryQuestionId]/organisation-funding-location.page.tsx
=> International added to funding location
